FROM maven:3.9.9-amazoncorretto-17-debian

RUN apt-get update \
 && apt-get install -y curl gnupg2 openssh-client \
 && apt-get update \
 && apt-get install -y wget gnupg2 \
 && curl -O https://dl.google.com/linux/linux_signing_key.pub \
 && gpg --dearmor < linux_signing_key.pub > /usr/share/keyrings/repo-archive-keyring.gpg \
 && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
 && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
 && apt-get update \
 && apt-get install -y google-chrome-stable \
 && apt-get install -y chromium-driver \
 && wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip \
 && apt-get install unzip \
 && unzip allure-2.29.0.zip -d /opt/ \
 && export PATH=$PATH:/opt/allure-2.29.0/bin \
 && ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure \
 && rm allure-2.29.0.zip \
 && wget http://ca.s7.ru/Group_Root.crt \
 && keytool -import -file Group_Root.crt -alias s7 -keystore /usr/lib/jvm/java-17-amazon-corretto/lib/security/cacerts -storepass changeit -noprompt \
 && apt-get remove --purge --autoremove -y curl gnupg2 \
 && apt-get remove --purge --autoremove -y wget gnupg2 \
 && apt-get remove --purge --autoremove -y unzip \
 && apt-get clean

WORKDIR /app


# Устанавливаем переменные окружения для headless Chrome
ENV CHROME_BIN=/usr/bin/google-chrome

# Запускаем тесты и генерируем отчет Allure
CMD ["sh", "-c", "export PATH=$PATH:/opt/allure-2.29.0/bin"]